create extension if not exists pgcrypto;
create table tenants (id uuid primary key default gen_random_uuid(), slug text not null unique, legal_name text not null, status text not null default 'active', plan_code text not null check (plan_code in ('up_to_500','up_to_1000')), customer_limit integer not null check (customer_limit in (500,1000)), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table users (id uuid primary key default gen_random_uuid(), email text not null unique, display_name text, auth_subject text unique, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table tenant_memberships (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references tenants(id), user_id uuid not null references users(id), role text not null check(role in ('owner','admin','staff','viewer')), status text not null default 'active', created_at timestamptz not null default now(), unique(tenant_id,user_id));
create table customers (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references tenants(id), external_ref text, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, unique(tenant_id,external_ref));
create table tenant_branding (tenant_id uuid primary key references tenants(id), card_title text not null, card_text text not null, primary_color text not null, secondary_color text not null, icon_asset_id uuid, logo_asset_id uuid, version integer not null default 1, updated_at timestamptz not null default now());
create table stamp_rules (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references tenants(id), name text not null, stamps_required integer not null check(stamps_required between 1 and 100), reward_title text not null, reward_description text not null, active boolean not null default true, version integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table cards (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references tenants(id), customer_id uuid not null references customers(id), public_token_hash text not null, status text not null default 'active', stamp_count integer not null default 0, revision integer not null default 1, rule_id uuid not null references stamp_rules(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(tenant_id,public_token_hash));
create table stamp_events (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references tenants(id), card_id uuid not null references cards(id), employee_membership_id uuid not null references tenant_memberships(id), quantity integer not null check(quantity between 1 and 10), reason text, idempotency_key text not null, created_at timestamptz not null default now(), unique(tenant_id,idempotency_key));
create table rewards (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references tenants(id), card_id uuid not null references cards(id), rule_id uuid not null references stamp_rules(id), status text not null default 'issued', issued_at timestamptz not null default now(), redeemed_at timestamptz);
-- Apply to every tenant table in production; web role must not own/bypass RLS.
DO $$ declare t text; begin foreach t in array ARRAY['tenant_memberships','customers','tenant_branding','stamp_rules','cards','stamp_events','rewards'] loop execute format('alter table %I enable row level security',t); execute format('create policy tenant_isolation on %I using (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::uuid) with check (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::uuid)',t); end loop; end $$;
