import type { Branding, Card, Reward, StampRule, Tenant } from './domain.js';
import { PLAN_LIMITS, capacity, hashToken } from './domain.js';

export class DemoStore {
  readonly mode = process.env.DATABASE_URL ? 'CONFIGURED_NOT_CONNECTED' : 'DEMO_NO_DATABASE';
  tenants = new Map<string, Tenant>(); cards = new Map<string, Card>(); rules = new Map<string, StampRule>(); rewards = new Map<string, Reward>(); branding = new Map<string, Branding>();
  constructor() { const tenant: Tenant = { id:'demo-tenant', slug:'demo', planCode:'up_to_500', customerLimit: PLAN_LIMITS.up_to_500 }; this.tenants.set(tenant.id, tenant); this.branding.set(tenant.id,{cardTitle:'StempelPass Demo',cardText:'Deine digitale Stempelkarte',primaryColor:'#155e75',secondaryColor:'#f0fdfa',version:1}); this.rules.set('demo-rule',{id:'demo-rule',tenantId:tenant.id,name:'Demo-Prämie',stampsRequired:10,rewardTitle:'Gratisartikel',rewardDescription:'Ein Gratisartikel deiner Wahl',active:true,version:1}); }
  capacity(tenantId: string) { const t=this.tenants.get(tenantId); if(!t) throw new Error('TENANT_NOT_FOUND'); return capacity(t, new Set([...this.cards.values()].filter(c=>c.tenantId===tenantId&&c.status==='active').map(c=>c.customerId)).size); }
  createCard(tenantId:string, customerId:string, ruleId='demo-rule') { const t=this.tenants.get(tenantId); if(!t) throw new Error('TENANT_NOT_FOUND'); if(this.capacity(tenantId).remaining<=0) throw new Error('CUSTOMER_LIMIT_REACHED'); const token=crypto.randomUUID()+crypto.randomUUID(); const card:Card={id:crypto.randomUUID(),tenantId,customerId,publicTokenHash:hashToken(token),status:'active',stampCount:0,revision:1,ruleId}; this.cards.set(card.id,card); return {card, token}; }
  publicCard(token:string) { const hash=hashToken(token); return [...this.cards.values()].find(c=>c.publicTokenHash===hash&&c.status==='active'); }
  stamp(tenantId:string, cardId:string, quantity:number, idempotencyKey:string) { const c=this.cards.get(cardId); if(!c||c.tenantId!==tenantId) throw new Error('CARD_NOT_FOUND'); if(!Number.isInteger(quantity)||quantity<1||quantity>10) throw new Error('INVALID_STAMP_QUANTITY'); c.stampCount+=quantity;c.revision++; const rule=this.rules.get(c.ruleId)!; if(c.stampCount>=rule.stampsRequired&&! [...this.rewards.values()].some(r=>r.cardId===c.id&&r.status==='issued')) { const reward:Reward={id:crypto.randomUUID(),tenantId,cardId:c.id,ruleId:rule.id,status:'issued'};this.rewards.set(reward.id,reward); return {card:c,reward,idempotencyKey}; } return {card:c,idempotencyKey}; }
  redeem(tenantId:string,rewardId:string) { const r=this.rewards.get(rewardId); if(!r||r.tenantId!==tenantId) throw new Error('REWARD_NOT_FOUND'); if(r.status==='redeemed') throw new Error('REWARD_ALREADY_REDEEMED');r.status='redeemed';return r; }
}
